### ISSUE TITLE
VS2019: Tests failing with `test class "tSQLt" or test name "TestUClass" could not be found`

### ISSUE THREAD

**Issue by ReinierKop** [GoEddie/tSQLt-TestAdapter#15]
I've tried to make the adapter work (using [this](https://www.sqlshack.com/tsqlt-framework-and-sql-server-database-project-integration/) tutorial) but I keep getting this message:

```
failure.message: The test class "tSQLt" or test name "TestUClass" could not be found or does not have the tSQLt test schema extended property
```

This looks a lot like I forgot to add extended properties, OR like tSQLt is not installed. However, the test I create in the linked tutorial does successfully run in the correct database in management studio.

I have made the exact same code work on a VS 2017 installation, which installs extension version 0.90 (rather than 0.91). I've checked the commit history in this repo for those version differences but I haven't been able to spot any glaring issues.

Can anyone reproduce and/or let me know what I am missing?

Version info:

* Visual Studio 2019 Community
* tSQLt-TestAdapter 0.91 (installed from within visual studio from the extension manager)
* tried on target Databases SQL Server 2014 and SQL Server 2017
* tSQLt V1.0.5873.27393

Sample project you can use to reproduce: [TestDbSolution.zip](https://github.com/GoEddie/tSQLt-TestAdapter/files/3658031/TestDbSolution.zip)

**Comment by GoEddie** [comment]
Sorry I just saw this, i'll take a look - might be a couple of days though :)

**Comment by ReinierKop** [comment]
Cool, no worries! Just to clarify a bit further: the test explorer in VS does get populated, but running any of the tests results in the error above.

**Comment by GoEddie** [comment]
Hi,

I have a fix for this that will let tests run from vs 2019 again, there is a preview vsix on the release page:

https://github.com/GoEddie/tSQLt-TestAdapter/releases/tag/0.99

If you could test it and let me know whether it fixes your issue not not that would be great.

I need to do some testing on VSTS as I am aware of a potential issue when using the adapter outside of visual studio so will check that first before pushing thins into the visual studio market place.
thanks,

ed

**Comment by ReinierKop** [comment]
Hey, sorry for getting back to you so late, I've been under the weather this last week. I've verified it's working on our machines now.

You can go ahead and close this if you want, or wait till the actual release, whichever you prefer.

 Thanks a lot for the fix!

**Comment by JayReally** [comment]
Hi Ed,

Following up on this issue, happy to test that fix as well. 

That release zip file doesn't seem to contain the .vsix I could install? Am I supposed to build the solution myself first (please bear with me if that is a dumb question ...)

**Comment by ReinierKop** [comment]
Hi Jay,

I indeed noticed this as well and decided to try out how much effort it'd be to build it myself. It's supereasy :)! 

1. Download the .zip from the release, 
2. Open the `.sln` in VS
3. Build the entire solution. 
4. You should then be able to find the `.vsix` file in `tSQLt-TestAdapter/XMLTestAdapterVSIX/bin/Debug/` (assuming you built the solution in the default Debug configuration)
5. double-click the .vsix and it should install as expected (it did for me).

If anything's unclear or not working let me know. I typed the above off the top of my head because the computer I used for building and testing is not available to me right now.

**Comment by JayReally** [comment]
Ah yes that's a reassurance. I tried in the past to build open sourced solutions, and had to give up after a couple of evenings of trying ;)

I'll give this version a shot in VS2019 and Azure DevOps which is where I want to use it mostly.

**Comment by GoEddie** [comment]
I forgot to upload it when I created the release!

I've pushed the updated version to the market place so if you get version 0.99 you should have the fix.

ec

**Comment by JayReally** [comment]
Hi Ed

I as able to re-test today; it now works fine in Visual Studio 2019 indeed, but I still have problems in my Azure DevOps pipeline

Doing nothing different than I did earlier with vs2017 projects. When run, the vs test task is listing all the .sql test files, but doesn't detect or run any "tests". 


Am I doing something wrong or is there still some issue with the new version? 
Attached some more info & log excerpt: [tsqlt test adapter issue - Copy.docx](https://github.com/GoEddie/tSQLt-TestAdapter/files/3803178/tsqlt.test.adapter.issue.-.Copy.docx)

Thanks a lot for your effort & sharing, I wish I could contribute but I really don't have that expertise...

**Comment by J-B-Sims** [comment]
You gotta publish your database test project first. Remember, the test is a stored procedure. Does the stored procedure exist in your database?
